### ISSUE TITLE
How should the program behave on a partial run?

### ISSUE THREAD

**Issue by RossBoylan** [RossBoylan/mccli#5]
Critical work can assume there will not be partial runs, and so this issue, though important, is not urgent.

A partial run is anything other than the traditional run that covers all iterations,
starting with 0, at one go.  Any of the following fit the description: 
  * rerunning a single failed iteration
  * running multiple simultaneous jobs/threads to do different simulations (e.g., 0-99 in one, 100-199 in another)
  * resuming a run after it died or you shut the computer down; running a simulation via a sequence of chunks.

There are at least 2 issues:
 1) If iteration 0 is not run first, everything else fails (cf #2 for an example).
 2) If a run starts after some other runs have finished (or possibly before), it currently asks whether to save previous work.  If you say yes, everything, including the previous iteration 0 files, is moved to a directory under `MC/saved_runs`.  This yields the first problem.  If you say no, it is unclear if there is a problem [there is; see next post]; it seems quite possible at least some output files will be overwritten, wiping out the results of previous chunks.

The whole previous framework seems based on the assumption that different runs represent different things: different parameters, different code, or something similar.  However, all my changes in repeatable are designed to allow partial runs that are all part of the same set of simulations.  **These 2 perspectives are at odds.**

The question about saving previous results is also problematic if the simulation is being run automatically, e.g., by a script that distributes the calculations, since the question requires user interaction.

So what is the desired behavior?

At the moment, the "Do you want to save the previous results" seems to be triggered by the presence of a non-empty
`MC/results/cumulative/directory/`.  At least, that's my guess about what the following code means:
```javascript
if (fs.existsSync(resultsDir) && fs.readdirSync(path.join(resultsDir,'cumulative')).length !== 0) {
```

**Comment by RossBoylan** [comment]
In point 2 of my original post I said it was unclear if there was a problem if you say "no" to the "save results" question.  I can now answer that: there is a problem.  Not a "some of my results aren't accumulated" problem but a "just won't run" problem.

Here's a session with a successful run of the first 2 simulations and then what happens when I do 2 more:
```
C:\Users\rdboylan\Documents\KBD2\mod91_test-MC-costs_ARG>node ..\mccli\bin\mc run 2 0 33
? do you want to save these results? (otherwise they will be written over) No
runSims.js: Iteration 0
simulations remaining: 1 eta:0.09mrunSims.js: Iteration 1
sum results
done
  simulations completed in 0 mintues!

C:\Users\rdboylan\Documents\KBD2\mod91_test-MC-costs_ARG>node ..\mccli\bin\mc run 2 2 33
? do you want to save these results? (otherwise they will be written over) No
runSims.js: Iteration 2
ERR montecarlo.py run failed
Traceback (most recent call last):
  File "C:\Users\rdboylan\Documents\KBD2\mccli\bin\js/../python/montecarlo.py", line 695, in <module>
    main()
  File "C:\Users\rdboylan\Documents\KBD2\mccli\bin\js/../python/montecarlo.py", line 32, in main
    datfile.save_raw_data()
  File "C:\Users\rdboylan\Documents\KBD2\mccli\bin\js/../python/montecarlo.py", line 168, in save_raw_data
    with open('MC/input_variation/dat_files/' + self.file_data['filename'] + '.csv', 'a',newline='') as totals_file:
FileNotFoundError: [Errno 2] No such file or directory: 'MC/input_variation/dat_files/b.csv'
```
For completeness, note that in mc init I said there were 2 iterations.  There is an outside chance the problems arose only because I exceeded that.

**Comment by RossBoylan** [comment]
An additional problem is how to combine all the results.  If you run 0-499 and then 500-1000 you will want the results for 0-1000, but the existing code just summarizes 500-1000 after that run.

Also, if the 2 runs are in parallel there are 2 potential timing issues, the first of which I've already mentioned:
  1) Run 0 must complete before any other run starts.
  2) Job 1000 may complete before all the other jobs finish.  It is not safe to start the final pass based on the completion of any job or any batch of jobs in isolation.

The solution to problem 2 seems to require separating out the final pass more clearly from the other work.  We obviously don't want to run it after each batch completes, which is what a naive parallelization would do.

**Comment by RossBoylan** [comment]
Summarizing the current behavior with partial runs:

1. Serial runs in the same directory (i.e., runs 0-500 and then 501-1000) will produce the question "Do you want to save the previous results" after the initial run.  If you say yes the previous results will be squirreled away and your later run will fail.  If you say no the run will also fail!  Even if it succeeded, it would not produce summary results that applied to the entire set of runs.  The one bright side is that, despite the dire warning about results being overwritten, the individual run results will not be overwritten since they have different names.
2. Parallel runs in different locations are possible (given sufficient copying of the original files), but combining the results is left as an exercise for the reader.  There are also some issues with run 0 being essential everywhere.  Copying the results from the first batch would be one solution.
3. Parallel runs in the same directory are not possible because the runs would be fighting over shared files.  Some of those shared files are non-obvious intermediate files generated by the `Fortran` program; they are neither inputs nor outputs.

It may be unclear what the desired behavior is, but I think it's clear the current behavior is not it :smiley:.
